BOT_ALLOWED_CHAT_CHANNELS = {
    "general",
    "kiba-logs",
    "kiba-bot",
}

BOT_DEFAULT_PREFIX = "!"

CHAT_COOLDOWN_SECONDS = 3.0
CHAT_RECENT_MESSAGE_LIMIT = 8
CHAT_SUMMARY_MESSAGE_LIMIT = 25
CHAT_SUMMARY_MIN_MESSAGES = 20

EXPENSE_PER_PAGE = 10
EXPENSE_LIST_TIMEOUT = 120
EXPENSE_RECENT_DEFAULT_COUNT = 5
EXPENSE_RECENT_MAX_COUNT = 10